{
 "title": "OPS-Gitlab",
 "description": "GitLab Performance Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Stuck import jobs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "events",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=", "value": "stuck_import_jobs" }
     ]
    }
   ]
  },
  {
   "title": "Avg Response Time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rails_transactions",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Email Triggered",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "events",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=", "value": "receive_email" }
     ]
    }
   ]
  },
  {
   "title": "Commit per Project in Master and Branch",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "path" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "events",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "Master" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=", "value": "push_commit" },
      { "condition": "AND", "key": "branch", "operator": "=", "value": "master" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "path" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "events",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "Branch" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=", "value": "push_commit" },
      { "condition": "AND", "key": "branch", "operator": "!=", "value": "master" }
     ]
    }
   ]
  },
  {
   "title": "Builds per Project",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "project" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "events",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "Project Name" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=", "value": "build_found" }
     ]
    }
   ]
  },
  {
   "title": "Background Thread Queue Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sidekiq_transactions",
     "select": [
      [
       { "params": [ "sidekiq_queue_duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Queue duration" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Commit TIme",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sidekiq_transactions",
     "select": [
      [
       { "params": [ "find_commit_real_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Avg  Commit Time" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Rails Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "alias": "usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rails_memory_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Background Thread Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "alias": "usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sidekiq_memory_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "rails",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rails_file_descriptors",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "sidekiq",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sidekiq_file_descriptors",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Method Call Counts",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "[[tag_method]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "method" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rails_method_calls",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Views Timings",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "[[tag_view]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "view" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rails_views",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Rails Transactions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "[[tag_action]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "action" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rails_transactions",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SideKiq Transactions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "[[tag_action]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "action" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sidekiq_transactions",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}